id: A434033F7
title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of Do Khyentsé
  Yeshé Dorjé
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:15:20.366688
  last_modified_at: 2022-03-01 00:15:20.366696
