id: A434033F7
title: Prayer for the Long Life of Pewar Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:15:20.369428
  last_modified_at: 2022-03-01 00:15:20.369434
